#!/usr/bin/env python3
"""
Makes data.js (the file the website reads) from the csv files in data/.
Run it after you change a csv:   python build_data.py
Coordinates come from geocode_cache.json (made by main.py) and data/extra_coords.json.
Only the towns used in the csv files get written out, so nothing else in the
cache (like places you searched from) ends up in data.js.
"""
import csv, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

# id, label, csv file, name column, conference column, venue column, sport
LEVELS = [
    ("fbs",        "FBS Football",          "fbs.csv",        "school", "conference", "stadium",  "Football"),
    ("fcs",        "FCS Football",          "fcs.csv",        "school", "conference", "stadium",  "Football"),
    ("baseball",   "D1 College Baseball",   "baseball.csv",   "school", "conference", "venue",    "Baseball"),
    ("basketball", "Men's Basketball*",     "basketball.csv", "school", "conference", "arena",    "Basketball"),
    ("mlb",        "MLB Baseball",          "mlb.csv",        "team",   "division",   "ballpark", "Baseball"),
    ("milb",       "Minor League Baseball", "milb.csv",       "team",   "league",     "ballpark", "Baseball"),
]

def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}

def main():
    coords = {}
    coords.update(load_json(os.path.join(HERE, "geocode_cache.json")))
    coords.update({k: v for k, v in load_json(os.path.join(DATA, "extra_coords.json")).items()
                   if not k.startswith("_")})

    venues, problems = [], []
    for lid, _, fname, ncol, gcol, vcol, _ in LEVELS:
        seen = set()
        with open(os.path.join(DATA, fname), newline="", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                school = r[ncol].strip()
                if school in seen:
                    problems.append(f"duplicate row skipped: {lid} / {school}")
                    continue
                seen.add(school)
                key = f"{r['city']}, {r['state']}, USA".lower()
                pt = coords.get(key)
                if not pt:
                    problems.append(f"no coordinates for {school} ({key}) - skipped")
                    continue
                venues.append({
                    "id": f"{lid}|{school}", "lv": lid, "s": school,
                    "c": r["city"].strip(), "st": r["state"].strip(),
                    "cf": r[gcol].strip(), "v": r[vcol].strip(),
                    "la": round(pt[0], 4), "lo": round(pt[1], 4),
                })

    levels = [{"id": x[0], "label": x[1], "sport": x[6]} for x in LEVELS]
    payload = {"levels": levels, "venues": venues}
    out = os.path.join(HERE, "data.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by build_data.py - edit the CSVs in data/, not this file.\n")
        f.write("window.STADIUM_DATA = " + json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + ";\n")
    print(f"Wrote {out}: {len(venues)} venues")
    for p in problems:
        print("  warning:", p)

if __name__ == "__main__":
    sys.exit(main())
