// Makes ../map.js (a small simple map of the US, Canada and Mexico).
// Data comes from the us-atlas and world-atlas packages (public domain).
// To run: npm i us-atlas world-atlas topojson-client, then node build_map.js
const fs = require('fs'), path = require('path');
const topo = require('topojson-client');
const read = p => JSON.parse(fs.readFileSync(require.resolve(p), 'utf8'));

// makes a line use fewer points (Douglas-Peucker)
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  const d2 = (p, a, b) => {
    let x = a[0], y = a[1], dx = b[0] - x, dy = b[1] - y;
    if (dx || dy) { const t = Math.max(0, Math.min(1, ((p[0] - x) * dx + (p[1] - y) * dy) / (dx * dx + dy * dy))); x += t * dx; y += t * dy; }
    return (p[0] - x) ** 2 + (p[1] - y) ** 2;
  };
  while (stack.length) {
    const [i, j] = stack.pop(); let max = 0, idx = -1;
    for (let k = i + 1; k < j; k++) { const d = d2(pts[k], pts[i], pts[j]); if (d > max) { max = d; idx = k; } }
    if (max > tol * tol) { keep[idx] = 1; stack.push([i, idx], [idx, j]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const flat = pts => pts.flatMap(p => [Math.round(p[0] * 1000) / 1000, Math.round(p[1] * 1000) / 1000]);
const rings = (geom, tol, minPts) => {
  const polys = geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : [];
  return polys.flatMap(p => p.map(r => simplify(r, tol))).filter(r => r.length >= minPts);
};
const lines = (geom, tol) => {
  const ls = geom.type === 'LineString' ? [geom.coordinates] : geom.type === 'MultiLineString' ? geom.coordinates : [];
  return ls.map(l => simplify(l, tol)).filter(l => l.length >= 2);
};

const us = read('us-atlas/states-10m.json');
const world = read('world-atlas/countries-50m.json');

const nation = topo.feature(us, us.objects.nation);
const land = [];
for (const f of (nation.features || [nation])) land.push(...rings(f.geometry, 0.012, 4));
for (const f of topo.feature(world, world.objects.countries).features) {
  if (!['124', '484'].includes(String(f.id))) continue;          // Canada and Mexico
  for (const r of rings(f.geometry, 0.05, 6)) {
    const lats = r.map(p => p[1]), lons = r.map(p => p[0]);
    if (Math.min(...lats) > 58 || Math.max(...lons) < -142 || Math.min(...lons) > -50 || Math.max(...lats) < 14) continue; // skip far north islands
    land.push(r);
  }
}
const borders = [];
borders.push(...lines(topo.mesh(us, us.objects.states, (a, b) => a !== b), 0.012));  // state lines

const out = { land: land.map(flat), borders: borders.map(flat) };
fs.writeFileSync(path.join(__dirname, '..', 'map.js'),
  '// Generated by tools/build_map.js from US Census / Natural Earth data (public domain).\nwindow.MAP_DATA=' + JSON.stringify(out) + ';\n');
console.log('rings', out.land.length, 'border lines', out.borders.length);
